### ISSUE TITLE
renaming old 0.3.0 leak LOL

### ISSUE THREAD

**Issue by voidinq1** [AnotherNoName/Cascade-0.3.7-SRC#2]

**Comment by GurteX** [comment]
i renamed ur mom

**Comment by AnotherNoName** [comment]
![rename](https://user-images.githubusercontent.com/65259492/206923038-12ca9a56-1435-42cf-b519-9ef6fbca0d9b.png)

**Comment by GurteX** [comment]
after a long investigation i found out that this issue is not actually true, i recently found out theres a bunch of stuff added and it is definitely not 0.3.0 but 0.3.7.
