### ISSUE TITLE
last time i ran something exactly like this i got ratted asf

### ISSUE THREAD

**Issue by Zane2b2t** [AnotherNoName/Cascade-0.3.7-SRC#4]
![image](https://user-images.githubusercontent.com/88916121/208096542-9381e6d7-26d7-47b7-8ad0-3cf68810d11c.png)

usally i ignore windows warning but last time i did for cascade i got ratted

**Comment by AnotherNoName** [comment]
i never found anything weird in the src, you can check it before you run it lol
